<?php

/**
 * @file
 * Contains advanced_search_defaults.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function advanced_search_defaults_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the advanced_search_defaults module.
    case 'help.page.advanced_search_defaults':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module contains default configs of view, blocks setup for Advanced Search') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function advanced_search_defaults_theme() {
  return [
    'advanced_search_defaults' => [
      'render element' => 'children',
    ],
  ];
}
